### ISSUE TITLE
Getting "404 Not Found" on a fresh install

### ISSUE THREAD

**Issue by rohit-ravikoti** [netlify/hydrogen-template#2] opened 2024-01-24 17:40 UTC
Hi there,

I'm getting the following error message when I do a fresh install of the app and run `npm run dev` locally.
<img width="736" alt="image" src="https://github.com/netlify/hydrogen-template/assets/16107563/e99c24b9-6b63-4382-a944-14f65a25e563">

**Comment by ascorbic** [comment] 2024-01-24 19:36
Thanks for the report. It loks liek soemhtign has changed recently. We'll look into this and get back to you.

FRA-237

**Comment by ascorbic** [comment] 2024-01-25 09:49
So it's not ideal, but the workaround is to save any file which will trigger a rebuild. CLosing this as a duplicate of https://github.com/netlify/remix-template/issues/134. Please follow that for updates.

**Closed as not planned by ascorbic** 2024-01-25 09:49 UTC

**Comment by ascorbic** [comment] 2024-01-30 11:25
@rohit-ravikoti if you update `netlify-cli` to `17.15.5` it should fix this. Thanks again for the report.
